"""create ingestion tables

Revision ID: 54d4867c8013
Revises: 
Create Date: 2026-03-28 18:11:59.351686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54d4867c8013'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetch_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('adults', sa.SmallInteger(), nullable=False),
    sa.Column('query_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('raw_offer_count', sa.Integer(), nullable=False),
    sa.Column('normalized_offer_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion'
    )
    op.create_table('normalized_flight_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fetch_run_id', sa.UUID(), nullable=False),
    sa.Column('route_key', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('offer_rank', sa.Integer(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('airline', sa.Text(), nullable=True),
    sa.Column('stops', sa.SmallInteger(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('departure_time_local', sa.Time(), nullable=True),
    sa.Column('arrival_time_local', sa.Time(), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fetch_run_id'], ['ingestion.fetch_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion'
    )
    op.create_table('raw_flight_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fetch_run_id', sa.UUID(), nullable=False),
    sa.Column('offer_rank', sa.Integer(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('airline', sa.Text(), nullable=True),
    sa.Column('stops', sa.SmallInteger(), nullable=True),
    sa.Column('duration_text', sa.Text(), nullable=True),
    sa.Column('departure_time_text', sa.Text(), nullable=True),
    sa.Column('arrival_time_text', sa.Text(), nullable=True),
    sa.Column('card_aria_label', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fetch_run_id'], ['ingestion.fetch_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_flight_offers', schema='ingestion')
    op.drop_table('normalized_flight_offers', schema='ingestion')
    op.drop_table('fetch_runs', schema='ingestion')
    # ### end Alembic commands ###
