"""create app flight alert events

Revision ID: bca04441d6f4
Revises: c515d7b19587
Create Date: 2026-04-28 20:21:12.660176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bca04441d6f4"
down_revision: Union[str, Sequence[str], None] = "c515d7b19587"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flight_alert_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("flight_watch_id", sa.UUID(), nullable=False),
        sa.Column("fetch_run_id", sa.UUID(), nullable=False),
        sa.Column("alert_type", sa.Text(), nullable=False),
        sa.Column("current_price", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("baseline_price", sa.BigInteger(), nullable=True),
        sa.Column("target_price", sa.BigInteger(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fetch_run_id"], ["ingestion.fetch_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["flight_watch_id"], ["app.flight_watches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flight_alert_events", schema="app")
    # ### end Alembic commands ###
